<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message>
        <source>CAD2PDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FitPageSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>End Arrow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportPdf.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeBackGround.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionEndpoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OCRExtractPageText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomIn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Start Arrow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>StampTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Strikeout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MenuHandTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageReplace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitPDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPages.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomOut.content</source>
        <translation></translation>
    </message>
    <message>
        <source>kxPdfLogoutTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MagnifyFontSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfInvoiceAssist.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightAndAnnotation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Superscript.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrab.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2Photo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PlaySlide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditPicNewTool_Rotate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslationSelect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeletePages.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageEnterEdit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Subscript.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Search.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionPath.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatClose.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatNavigationBar2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignDot.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClockwiseDoc.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EnterSuperNoteMode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LastPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HideNavigationPannel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Cloudy.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2Office.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Line Style.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Annotate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageCorrectFinished.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormFillingDate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditTextExit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontName.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CADTOPdf.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2PPT.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatZoomIn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Underline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBoxAlpha.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WaterMarkTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2CAD.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LastPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NextPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Italic.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBoxBkColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RotateToTheRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Open.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Markdown2PDFTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditPageHeaderFooter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslationSelect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomOutThumbnails.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageCorrectExit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSign.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookSelfAdaptionPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFTOCad.content</source>
        <translation></translation>
    </message>
    <message>
        <source>m_LineSpacing.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FirstPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditTransparency.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoClipPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageClip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace Text.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportPdf.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NavigateBack.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClipPageRange.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SaveAs.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MenuFloatToolBar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Shapes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearFormat.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Shape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FitPageSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewImage2top.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditReplace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoClipPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddBookMark.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2Office.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageClip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AnnotGraffiti.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontName.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AreaHighlight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AddHeaderFooterTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignCross.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookIncreaseFont.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPagesFromDoc.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CancelImageClip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookDecreaseFont.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatFitWidth.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditPageHeaderFooter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddPageNumberTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Markdown2PDFTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Page Number.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSLogoutTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PolyLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClipPageRange.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CompleteClipPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VerificationSignature2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToPDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignatureEmbedBatch.content</source>
        <translation></translation>
    </message>
    <message>
        <source>End Arrow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignatureApplyMultiPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CorrectionFluid.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatNavigationBar2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SaveAs.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Line Width.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextQuery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FullScreen.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBold.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiDeleteAll.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditImage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Arrow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiEraser.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeBorderColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextUnderline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAddText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Square.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Stamp.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditReplace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LetterSpace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Annotate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditPicNewTool_Rotate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RandomDraw.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EnterSuperNoteMode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>XiuTangH5Tip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslationSelectPdf.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportHighlight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditImage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfNewEdit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasurePerimeter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatBrush.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom Page.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditBackGround.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightAndAnnotation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSign_FreeText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertBlankPages.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2CAD.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2PPT.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatNavigationBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Search.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Square.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddHeaderFooterTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FitHeight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Clockwise.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiHline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookSelfAdaptionPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBar_PageCorrectFinished.content</source>
        <translation></translation>
    </message>
    <message>
        <source>XiuTangH5Tip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AreaHighlight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WaterMarkTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiVline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PlaySlide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFCompress.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>kxPdfLogoutTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageRotate90.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignatureEmbed.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookDecreaseFont.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractTextCopyPic.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageExitEdit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureArea.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LineSpace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerURLEntranceTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfReplacePages.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewFromMDTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignatureDelete.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NavigationBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Page Select.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatFitSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClockwiseDoc.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TBLineStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditTransparency.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Counterclockwise.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignCheck.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocTranslate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiHline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CreatePdf.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatZoomOut.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Subscript.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CreatePdf.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Italic.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LineSpace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookSinglePage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Circle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Encrypt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Squiggly Underline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfElectronicInvoicePrint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FreeText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Stamp.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionMidpoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UpdateHeaderFooterTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CompleteClipPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBar_PageCorrectExit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClipPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportWeiboImageCmd.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignCross.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2TXTConvert.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FitVisible.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextCommentBox.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageReverse.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBoxBorderColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageReplace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPagesFromDoc.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FitWidth.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageRotate90.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextQuery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureScale.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomInThumbnails.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergePDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OS_PhoneShare.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Quick_PageDelete.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageEnterEdit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PreviousPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergePDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocTranslate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoWheel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextCommentBox.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReplaceBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditTextToolBarTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoWheel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteHeaderFooterTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatHandTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageCorrectManualAdjust.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideAnnotations.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InterceptSelectedArea.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditContent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractTextCopyText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatHandTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageClip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormFilling.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBoxAlpha.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Squiggly Underline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Quick_PageInsert.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAddText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiVline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>StrikeoutBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewImage2Bottom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignCircle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractTextCopyText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomOutThumbnails.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2Excel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeletePages.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearFormat.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Print.title</source>
        <translation></translation>
    </message>
    <message>
        <source>StampTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageDelete.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageOpacity.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RotateToTheLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageOcrExtract.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomIn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextStrikethought.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Bold.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Find.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatClose.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditFlip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TemplatesPrint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiEraserWholeType.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UnderlineBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AttachmentTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageReverse.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ContinuousRead.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextItalic.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Line Style.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImagePreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Shape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>IndentFisrtLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UnderlineBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VerificationSignature.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Counterclockwise.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FullScreen.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Page Select.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureDistance.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Page Number.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2Excel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Polygon.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomOut.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MenuFloatToolBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingMode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSign_FreeText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextUnderline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditContent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Note.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Save.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureArea.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomClipPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OS_PhoneShare.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfReplacePages.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PolyLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentFix.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfNewEdit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageCorrectFinished.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WaterMark.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Recommended PictureToText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiDeleteAll.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CompressTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IndentFisrtLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NavigateForward.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Shapes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatFitWidth.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractTextCopyExcel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EyeShield.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatFitPageSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageOcrExtract.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SinglePageContinuous.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditDelete.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2Photo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NavigateBack.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionPath.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookDoublePage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerURLEntranceTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignCircle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFExtractPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslationSelectPdf.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MagnifyIndentation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignDot.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ConfirmImageClip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomInThumbnails.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfElectronicInvoicePrint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReduceFontSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Strikeout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditBackGround.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TwoPageContinuous.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSign.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslationAll.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomClipPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReplaceBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocPermission.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Pdf2PhotoCmd.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasurePerimeter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Superscript.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Arrow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionIntersection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReduceIndentation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormFilling.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AttachmentTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageExitEdit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditFlip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowAnnotations.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddImage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FileCollect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignatureDeleteBatch.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OCRExtractText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitPDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MenuSelectionTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Circle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfInvoiceAssist.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteHeaderFooterTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditTextToolBarTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddPageNumberTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatZoomIn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TemplatesPrint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PreviousPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Encrypt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureDistance.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Strikethrough.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatFitPageSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Translation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UnderlineAndAnnotation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Cloudy.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FitVisible.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Pdf2PhotoCmd.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageExtractTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFCompress.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageClip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Translation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NoteBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageEditDelete.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBold.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace Text.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InterceptSelectedArea.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Polygon.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FitWidth.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditTextExit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NavigationBar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ContinuousRead.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookSinglePage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDF2TXTConvert.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatSelectionTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureScale.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSLogoutTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AddBookMark.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MagnifyFontSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Strikethrough.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBoxBorderColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReduceFontSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignature.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VerificationSignature2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LetterSpace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AnnotGraffiti.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Start Arrow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VerificationSignature.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Photo2PDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionIntersection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBoxBkColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HyperLink.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiEraserPartType.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractTextCopyPic.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NextPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TBLineStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Highlight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocPermission.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageCorrectExit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideAnnotations.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowAnnotations.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MenuSelectionTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImagePreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AIOCR2PDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SinglePageContinuous.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewFromMDTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CorrectionFluid.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CombinePDFTips.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Highlight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBar_PageCorrectFinished.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiEraserWholeType.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Clockwise.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Note.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OCRExtractText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureResultPanel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReduceIndentation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportWeiboImageCmd.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Open.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClipPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OCRExtractPageText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextItalic.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom Page.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FileCollect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillSignCheck.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AIOCR2PDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPages.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiDraw.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractTextCopyExcel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataRecover.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ActualSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportHighlight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertBlankPages.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EyeShield.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewImage2Bottom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslationAll.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFExtractPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Save.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookDoublePage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ActualSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TBLineWidth.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Line Width.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFEditText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OcrExtractScrawl.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiEraser.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Quick_Clockwise.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MagnifyIndentation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewImage2top.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiDraw.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraffitiEraserPartType.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MenuHandTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideNavigationPannel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CompressTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NavigateForward.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Quick_Counterclockwise.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBar_PageCorrectExit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatSelectionTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeBackGround.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RandomDraw.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowNavigationPannel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Underline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionEndpoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Find.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RotateToTheLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFAdsorptionMidpoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfImageOpacity.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatBrush.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextStrikethought.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DataRecover.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CADTOPdf.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NoteBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddImage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Bold.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToWord.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingMode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>m_LineSpacing.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToWord.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowNavigationPannel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageCorrectManualAdjust.content</source>
        <translation></translation>
    </message>
    <message>
        <source>UpdateHeaderFooterTips.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImageExtractTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatZoomOut.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TwoPageContinuous.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CAD2PDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>StrikeoutBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrab.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormFillingDate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WaterMark.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentFix.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFMeasureResultPanel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EbookIncreaseFont.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PdfSignature.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatFitSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeBorderColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TBLineWidth.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FitHeight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UnderlineAndAnnotation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Print.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FreeText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FloatNavigationBar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFTOCad.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Recommended PictureToText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HyperLink.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Photo2PDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FirstPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageDelete.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToPDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RotateToTheRight.content</source>
        <translation></translation>
    </message>
</context>
</TS>
