<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message>
        <source>EquationProfessional.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureDesign.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SpeedLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartCombination.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CloseWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineDiagramMoreTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOfficespaceLoginFailTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarAddChartElement.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OneStepSaveTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextToDiagram.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DOnOff.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartScatter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OneStepSaveTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatObjectSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextboxBeautify.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureDesign.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartBubble.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertBarcode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CloseDevelopmentTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrab.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BringForward.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RunJSMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HardwareEncryption.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IntranetVersion DocerURLEntranceTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DOnOff.title</source>
        <translation></translation>
    </message>
    <message>
        <source>JavaScriptEditor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeHeight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertProcesson_Flow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationOperatorGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerHomeEntranceTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontName.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DonateMoney.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TriggerExtendObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Auto_Backup_xa.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TriggerExtendObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Italic.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSHomepageTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Print2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtOutline2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltDown.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExplorVersion.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SendBackward2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtGalleryQuickBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArt ChangeLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSSaveFileTocloudTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineIcons.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertMap.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DDepthMenu.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Sentence Translation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_MoreControls.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationDelimiterGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartPie.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Themes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MoveChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontName.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditShape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSDocShare.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOpenCloudFileTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Print2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextToDiagram.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeWidth.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSUserLoginCloudTextBtnTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFontOutline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentSecurityCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToPDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineFonts.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineIcons.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Auto_Backup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DescriptionDevelopmentTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OfflineManagement.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartArea.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DonateMoney.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LinkShareTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartGallery_pro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSCloudFeedbackTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowDown.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchRowCol.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_TextTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToolsDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureSetTransparentColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSUserLogoutCloudTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Theme Fonts.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_PictureTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineFonts.content</source>
        <translation></translation>
    </message>
    <message>
        <source>XiuTangH5Tip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureOutline2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartElements.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSDocShare.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtStyles.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_PictureTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationDelimiterGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChooseDataSource.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOfficespacePsaawordTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArt InsertBullet.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltDown.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ksoTextFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationLimitGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearFormats.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSymbol.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSymbol.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>XiuTangH5Tip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtOutline2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarFormatChartArea.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ksoTextFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExplorBackupDir.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MarkVersion.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Ornamentation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerURLEntranceTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Sentence Translation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddPicFrame.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CollapseQuickBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSUserLoginCloudTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CloseWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarChartStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchJS.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchVB.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Italic.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationInsertGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtFill2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>XieDeTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Protect_Eyes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtGalleryQuickBar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearTableStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Theme Colors.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationScriptGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartGallery_pro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SendBackward.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSCloudInformationTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertProcesson_Flow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeAutoShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PPTCustom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Theme Effects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSymbol_Pro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartColumn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowOnOff.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BringForward2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartStock.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtQuickBarCollapse.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSUserLoginCloudTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OS_PhoneShare.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSRoamingfileTip_pro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DescriptionDevelopmentTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarChartFilters.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationNormalText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CloudFormTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSRoamingfileTip_WPSCloud.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArt MoveShape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Ornamentation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationLargeOperatorGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtSameLetterHeights.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Theme Colors.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SendBackward2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartRadar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Auto_Backup_xa.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DDepthMenu.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Print.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TransformQuickBar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureCrop.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSRoamingfileTip_pro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HardwareEncryption.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddChartElements.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Auto_Backup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationIntegralGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Cut.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Bold.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchRowCol.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSRoamingfileTip_WPSCloud.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_Property.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArt MoveShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtShapePalette.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationProfessional.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImagePreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArt ChangeLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtOutline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtQuickBarExpand.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Protect_Eyes_Night.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CloseOtherWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_Property.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CloseOtherWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartStock.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationLinearFormat.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChooseDataSource.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_MoreControls.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentAuthente.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DSurfaceMenu.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OS_PhoneShare.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureOutline2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeChartType.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartCombination.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerMall.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureSetTransparentColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Themes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DStylePalette.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentAuthente.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSymbol_Pro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SendBackward.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IntranetVersion DocerURLEntranceTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Autobackup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PPTCustom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExplorVersion.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoVersion.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditPoints.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtFill2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSCloudInformationTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowDown.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureChange.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerURLEntranceTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSRoamingfileTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertBarcode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangePicture.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOfficespaceRegPsaawordTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOfficespaceRegPsaawordTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddPicFrame.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationOperatorGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationFunctionGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineDiagramMoreTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationOptions.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DStylePalette.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSmartDiagram.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartColumn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtVerticalText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerHomeEntranceTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExpandQuickBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowUp.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Night_Mode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineTextboxMore.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowPalette.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureAdjust.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocPermission.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSmartDiagram.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationOptions.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartElementFormat.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFormatStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Cut.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFormatStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartScatter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertOnlinePictureFromFile.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltUp.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSSaveFileTocloudTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarFormatChartArea.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BringForward.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowUp.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureFill2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationNormalText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartPie.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationRadicalGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureAdjust.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocPermissionProtection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LinkShareTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Theme Effects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VisualBasicEditor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSCreatecloudLinkTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetToFitStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationAccentGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineIconMore.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationFractionGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationFunctionGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureFill2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchVB.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSCloudFeedbackTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertQRCode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>JavaScriptEditor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_ViewCode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Autobackup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Protect_Eyes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationLargeOperatorGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TouchUiMode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MoveChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineTextboxMore.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartBar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtStyles.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineIconMore.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtOutline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRelationshipDiagram.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_TextTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationLinearFormat.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertQRCode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarAddChartElement.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExplorBackupDir.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartBubble.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeHeight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SwitchJS.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationRadicalGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BringForward2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOfficespaceLoginFailTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertProcesson_Mind.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Copy.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPictureFromFile.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToolsDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationFractionGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Photo2Pdf.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationInsertGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSRoamingfileTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenRecording.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertMap.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CloudFormTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSDocShareAsPDF.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSHomepageTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VisualBasicEditor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocPermission.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangePicture.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartArea.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationScriptGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureOutline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImagePreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DTiltUp.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationAccentGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SpeedLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_ViewCode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRelationshipDiagram.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditPoints.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowPalette.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSDocShareAsPDF.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOpenCloudFileTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSCreatecloudLinkTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSUserLoginCloudTextBtnTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearFormats.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataRecover.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MarkVersion.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextboxBeautify.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoVersion.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeWidth.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtVerticalText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationMatrixGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeChartType.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtSameLetterHeights.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NudgeShadowRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatObjectSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArtInsertShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeAutoShape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureChange.content</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarChartFilters.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtShapePalette.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationLimitGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenRecording.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DSurfaceMenu.content</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSUserLogoutCloudTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>XieDeTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataRecover.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartRadar.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TransformQuickBar.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Bold.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPictureFromFile.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertOnlinePictureFromFile.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Copy.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetToFitStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CloseDevelopmentTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFontOutline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentSecurityCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartElements.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AddChartElements.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrab.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartArt InsertBullet.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocerMall.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureOutline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>KOSOfficespacePsaawordTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TouchUiMode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertProcesson_Mind.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditWordArtText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationIntegralGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearTableStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocPermissionProtection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Protect_Eyes_Night.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureCrop.title</source>
        <translation></translation>
    </message>
    <message>
        <source>QuickBarChartStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OfflineManagement.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowOnOff.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Theme Fonts.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Print.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartElementFormat.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RunJSMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationMatrixGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Photo2Pdf.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditWordArtText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Night_Mode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToPDF.content</source>
        <translation></translation>
    </message>
</context>
</TS>
