<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message>
        <source>EditConnectionProperties.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ComAddin.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Macros.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageLayoutDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertTextboxHorizontal2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Translate Image.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignDistributed.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditCloumns.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LockTitleRows.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_PictureTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GrowFont.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoFilterAnalysis.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TopAndBottomBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ColumnSparkline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitMerge.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatPainter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WorkSheet.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearFilter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTSubtotals.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterMoreSetup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintDirect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FuncCatMoreFunctions.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineConvertToLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterCopies.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PercentStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomViews.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertFunction.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Eraseborder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetPicture.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertFunction.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TopBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Average.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NamePaste.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Accounting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowPrecedents.content</source>
        <translation></translation>
    </message>
    <message>
        <source>What-If%20Analysis.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FuncCatText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertFileObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WindowReset.content</source>
        <translation></translation>
    </message>
    <message>
        <source>StopRecordMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AllowEditRanges.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Subtotals.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Layout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_ConditionHighlight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddFavorite.title</source>
        <translation></translation>
    </message>
    <message>
        <source>m_Format.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTFieldSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LineSparkline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPageBreakHelper.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BandedRows.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Paste.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NoBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BottomDoubleBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineMarkers.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerItemWidth.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TotalRow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecentLineWrap.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageSetup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CircularReferences.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Validation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataSort.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_WordArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Align.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NormalViewEt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Underline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Paste2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_DesignMode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableMenuRefresh.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineGroup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LinkedDataTypeListPanel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Min.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VerbSideBySide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Macros.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FirstColumn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowDependents.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowDetail.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCenter2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShareWorkbook.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTHideFieldList.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OutsideBorders.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignDistributed.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertFileObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VAlignTop.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImportTxt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTShowDetail.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineUnGroup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RelativeReference.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Chart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WindowReset.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TopBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PreviousComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FullScreenMode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecordList.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageSetup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ColumnsCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DevelopmentTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertClipArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Hyperlink.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WorkSheet.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Security.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToExcel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DynamicShape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CharacterSpacing.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignJustify.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineConvertToColumn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Paste.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReapplyFilter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PagePreviewSwitch.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DisplayHeadings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReapplyFilter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideDetail.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AdvancedFilter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ImportTxt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Copy.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Consolidate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MathAndTrig.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Data.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DoubleAccounting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPictureFromFile2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineUnGroup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TotalRow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RemoveDuplicates.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerCaption.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRange.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Camera.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineFirstPoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BottomBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Home.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WorkSpace_Backup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Align.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Paste2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintArea.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerColumn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Currency.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NextComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFillColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowAllComments.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Margins.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTHide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintNormalView.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetCommentAnchor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Thesaurus.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FuncCatMoreFunctions.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterCollate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NumberFormatCells.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextToColumns.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Slicer.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PagePreviewSwitch.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineCooperation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTHide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Group.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InteractiveChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShareWorkbook.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToPPT.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowAllComments.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LTRTextDirection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RTLTextDirection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSum.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawingToolsDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LockAspectRatio.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_On.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VerbSideBySide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SendFileTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageZoom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RowsAndColumn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CmpSideBySide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignmentFormatCells.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineConvertToWinLoss.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GrowFont.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Legend.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecordMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DoubleUnderline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTHideDetail.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTableAnalysis.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAsTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTRepeatLabels.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NormalViewEt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TaskWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawGrid.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowFormulas.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_ConditionHighlight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OutlineSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>StopRecordMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearFilter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecalculateBook.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Refresh.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineLowPoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineConvertToWinLoss.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintTitle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintArea.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ConditionalFormatting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableMenuRefresh.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerColumn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>What-If Analysis.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LookupAndReference.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLineColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Table.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomViews.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Count.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShrinkFont.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableName.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RB_Clipboard.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Eraseborder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VAlignCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Legend.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DataTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrabOcr.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MathAndTrig.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTSortAndTopTen.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HideWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowPrecedents.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Clear.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BookProtection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageLayoutDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ThickBottomBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearArrows.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineSeriesColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EnableMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OutlineSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Direction.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Printer.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlighDuplicates.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoFilterFavorite.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintHeaderFooter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintGridlines.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerCaption.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintHeadings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Clear.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataUngroup2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetPicture.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CircularReferences.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CommaStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterPaperSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTTableOptions.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseIndent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFillColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Validation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterCopies.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditCloumns.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DisplayHeadings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTableOrder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BandedRows.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Recommended Chart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevLandscape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportWeiboImageCmd.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Duplicates.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VerticalText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartObjects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ContextTextDirection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Recommended Chart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTRefreshAllData.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CmpSideBySide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SortAscending.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DataDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NameCreate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SameLetterHeights.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Logical.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_WordArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertDropDownList.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportFilterResult.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PublishToSharePoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CalculateSheet.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Refresh.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_Off.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatChartObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineNegativePoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FillColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AllowEditRanges.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NamePaste.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImportData.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertTextboxHorizontal2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LinkedDataTypeListPanel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTFieldSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RowsAndColumn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotChartAnalysis.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RefreshAll.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SpellCheck.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitSheet.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPageBreakHelper.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteRange2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChineseTranslation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseIndent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseIndent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SortDescending.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToExcel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ProtectAndShare.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FreezePanes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SourceData.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderRow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextToColumns.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChineseTranslation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AllBorders.content</source>
        <translation></translation>
    </message>
    <message>
        <source>m_Format.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeSheet.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Morefunctions.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FreezePanes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PublishToSharePoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPortrait.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ImportData.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitPanes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RelativeReference.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormsToolbox.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Security.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RecenttlyUsed.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Average.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FlashFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineConvertToColumn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoFilter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowDetail.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFill2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DoubleUnderline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UnhideWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EvaluateFormula.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerItemHeight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShrinkFont.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Count.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Chart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>What-If Analysis.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WinLossSparkline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeColumns.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLineColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowOrHideComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ThickBoxBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterCollate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignThaiDistributed.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTableOrder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Scientific.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InteractiveChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FuncCatDateAndTime.content</source>
        <translation></translation>
    </message>
    <message>
        <source>UnhideWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLineColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineClear.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillAndOutLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ComAddin.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderFooter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SeriesInRows.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Find.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderFooter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SortDescending.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ConditionalFormat.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowFormulas.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EnableMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FTB_Property.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Lighting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Ai Matting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparkAxis.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RefreshAll.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExistingConnections.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitSheet.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FlashFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LoadMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ContextTextDirection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrabOcr.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Margins.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ThickBoxBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Gallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LockCell.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NumberFormatGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTSortAndTopTen.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DoubleAccounting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SortAndFilter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SeriesInColumns.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Table.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawingToolsDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineEditGroupData.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTFilterConnections.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Lighting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPictureFromFile2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTFilterConnections.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CellStyleGallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SeriesInRows.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FTB_Property.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageOrientation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RightBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTNotRepeatLabels.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextOrientation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VAlignTop.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslateToSimplifiedChinese.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageBreakPreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AdvancedFilter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormulaErrorCheck.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CommaStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LockSideBySide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineNegativePoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NameManager.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RunMacro2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChartObjects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RecentLineWrap.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSum.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentFix.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_On.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EDRProperties.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_DrawingTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_AutoSum.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoFilter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataGroup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentSlimming.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCancel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTNotRepeatLabels.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Duplicates.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResizeTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_AutoSum2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PercentStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CellStyleGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BandedColumns.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Camera.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Currency.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatChartObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_AutoSum.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitMerge.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NoBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VAlignBottom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Group.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SeriesInColumns.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NameDefine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTRepeatLabels.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HideDetail.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterPaperSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RecordList.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineCooperation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataGroup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DisplayGridlines.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OutsideBorders.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslateToTraditionalChinese.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertWordArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeColumns.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ModifyPivotTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormulaErrorCheck.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineLowPoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DuplicateItemsManager.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HomeDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RB_Clipboard.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightDisplay.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageLayoutView.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Translate Image.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LastColumn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageOrientation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageBreakPreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontFormatCells.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoFilterFavorite.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLineColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VAlignBottom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillAndOutLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineClear.content</source>
        <translation></translation>
    </message>
    <message>
        <source>StopAutoVersion.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertWordArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DuplicateItemsManager.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTableDelete.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddFavorite.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageZoom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowDependents.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TopAndBottomBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BottomDoubleBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Accounting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DataUngroup2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HomeDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FirstColumn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_AutoSum2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCenter2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RotateRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRange2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Direction.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FTB_EditCode.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SheetBackground.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerItemWidth.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LastColumn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TopAndThickBottomBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSlicer.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Scientific.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevNextPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPageBreak.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Min.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Max.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RTLTextDirection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Printer.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertPageBreak.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintTitle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LockAspectRatio.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TrackChanges.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineMarkers.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerReportConnection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLineColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreviewZoomCombo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterSide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TrackChanges.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BottomBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SameLetterHeights.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LTRTextDirection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExitPreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TaskWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FTB_EditCode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreviewMargins.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ConditionalFormat.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetAllCommentsAnchor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ColumnsCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintHeadings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecordMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ProtectSheet.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NameManager.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Thesaurus.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterMoreSetup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LockTitleRows.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLineColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ProtectSheet.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_DrawingTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_PictureTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineSeriesColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ConditionalFormatting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Connections.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EDRProperties.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineMarkerColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineEditGroupData.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ThickBottomBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAsTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPortrait.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RunMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ConvertToRange.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Max.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTRefreshData.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FillColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintNormalView.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextOrientation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFillColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteRange2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTSubtotals.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Home.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ObjectSelect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTTableOptions.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CalculateSheet.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Gallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NumberFormatCells.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LoadMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFillColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRange2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VerticalText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ObjectSelect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignmentFormatCells.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CompressPictures.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SortAscending.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTHideFieldList.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerSetting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LookupAndReference.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitPanes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageLayoutView.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintHeaderFooter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditCrossBookLinks.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Ai Matting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>StopAutoVersion.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Financial.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineFirstPoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPreviousPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ClearArrows.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslateToTraditionalChinese.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationEditor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Copy.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LeftBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Morefunctions.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OtherBorders.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseDecimal.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseIndent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CharacterSpacing.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FuncCatDateAndTime.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ProtectAndShare.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OtherBorders.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LockSideBySide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TopAndDloubleBottomBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>What-If%20Analysis.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExistingConnections.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawBorder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseDecimal.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Hyperlink.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreviewZoomCombo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteRange.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineLastPoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerReportConnection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Slicer.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LockCell.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SourceData.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFill2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineConvertToLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResizeTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeSheet.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AllFunction.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CTB_DesignMode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ColumnSparkline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DynamicShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineHighPoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineLastPoint.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AllBorders.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditConnectionProperties.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportWeiboImageCmd.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NextComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingLayout2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AllFunction.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecalculateBook.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SheetBackground.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTShowDetail.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowOrHideComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTableDelete.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BookProtection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevLandscape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlighDuplicates.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPreviousPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TranslateToSimplifiedChinese.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WinLossSparkline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Consolidate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RotateRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RightBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NumberFormatGallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LeftBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LineSparkline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertClipArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCancel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Subtotals.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineHighPoint.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DevelopmentTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RemoveDuplicates.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Logical.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignThaiDistributed.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertDropDownList.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PTHideDetail.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VAlignCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DataTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreviewMargins.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FuncCatText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTRefreshData.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WorkSpace_Backup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PTRefreshAllData.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataUngroup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PreviousComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RunMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EditCrossBookLinks.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLineColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerSetting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetCommentAnchor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CompressPictures.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightDisplay.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoFilterAnalysis.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentSlimming.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Underline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Fill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Find.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Financial.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertTextboxHorizontal.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotChartAnalysis.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ConvertToRange.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingLayout2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineMarkerColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteRange.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DisplayGridlines.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterSide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SparkAxis.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToWord.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportFilterResult.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EvaluateFormula.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetAllCommentsAnchor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToWord.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertTextboxHorizontal.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormsToolbox.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FullScreenMode.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontFormatCells.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignJustify.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ModifyPivotTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ArtisticWordAlignment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TopAndDloubleBottomBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSlicer.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatPainter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentFix.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SpellCheck.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintDirect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationEditor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataUngroup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Fill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeSelection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseDecimal.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseDecimal.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecenttlyUsed.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeSelection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableName.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlicerItemHeight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLineColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Data.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BandedColumns.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRange.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExitPreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ArtisticWordAlignment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RunMacro2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Connections.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TopAndThickBottomBorder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Layout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawGrid.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PivotTableAnalysis.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevNextPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToPPT.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SendFileTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_Off.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintGridlines.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SparklineGroup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NameDefine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderRow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SortAndFilter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NameCreate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataSort.title</source>
        <translation></translation>
    </message>
</context>
</TS>
