<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message>
        <source>Translate Image.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitMerge.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AnimationSchemes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatPainter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_OutlineView.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideOrientation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomFit.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Zoom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintDirect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeDiagramColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertDateTime.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetPicture.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MorePrintSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintingOrder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeShapes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Superscript.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartChoice.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertFileObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AddSubordinate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Subscript.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Arrange.title</source>
        <translation></translation>
    </message>
    <message>
        <source>weibotool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFill2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_6.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Normal.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowHideGrid.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Paste.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLine2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_Slides2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageSetup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideDesign.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawAlignTop.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TaskPane.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Rotate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_WordArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertColumnsRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToImage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtAlignment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFontColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPrintHiddenSlide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Underline.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawAlignTop2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RecentFillColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFill2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSmartArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WebPreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ArrangeAll.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioPlay.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_9.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_3.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_4.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_1.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_6.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioBegin.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ColorScheme.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToImage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBox.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TransitionEffect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertFileObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LineBreak.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SetUpShow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignTop.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Ruler.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageSetup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RB_Font.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DevelopmentTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertClipArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRowsAbove.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Hyperlink.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Security.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeDiagramColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToExcel.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DynamicShape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Package.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Paste2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtAlignment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TransitionEffect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteMember.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransApplyToAll.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Macros.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Home.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WorkSpace_Backup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DuplicateSlide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideMasterClose.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PaperSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoPlay.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_Slides.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AnimationPainter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NextComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FooterPlaceHolder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HideAudio.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderPlaceHolder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LoopAudio.content</source>
        <translation></translation>
    </message>
    <message>
        <source>weibotool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_4.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Thesaurus.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBox2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Markup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Arrange.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TraditionalChinese.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FontAlignMenu.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineCooperation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Paste2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioAcrossPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Group.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InteractiveChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeDiagramStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>importtemplates.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToPPT.content</source>
        <translation></translation>
    </message>
    <message>
        <source>R2LTextDirection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>L2RTextDirection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FitTextTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextDirection.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawAlignLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawingToolsDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideLibrary.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LockAspectRatio.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_On.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DistRowSevenly.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SendFileTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MasterLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_PictureTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeDiagramNum.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideLayouts.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShowFromCurrent2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BordersFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawAlignTop2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WppSharePlay2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpsAssistMagic.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtCharacterSpacing.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewSlideMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewTitleMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_PictureTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintDuplex.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFill2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>modelessay.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Rotate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PreviewPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideImage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_3.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawAlignLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToVideo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideOrientation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_OutlineView.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Rehearse.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpsAssistOnlineTemplate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransDuration.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddCoworker.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLine2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Media.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewDash.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevFrameSlides.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomCombo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransition.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SkipSlide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomShows.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Color.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Sound.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FooterPlaceHolder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_Slides.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Package.content</source>
        <translation></translation>
    </message>
    <message>
        <source>BackgroundMusic.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RB_Clipboard.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LineSpacing.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrabOcr.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WordArtCharacterSpacing.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertTable.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SaveBackgroundPicture.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewSlide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SelectAll.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>COMAddIns.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocTranslate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Paragraph2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Direction.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Select.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Subscript.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CheckSpelling.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioFadeIn.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevClose.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HandoutMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLine2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Section.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SimplifiedChinese.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Delete.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Ruler.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Justify.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Color.title</source>
        <translation></translation>
    </message>
    <message>
        <source>UsePresenterView.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawAlignTop.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>COMAddIns.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeShapes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetPicture.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WppSharePlay.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseIndent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoBegin.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseSpace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioTrim.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevLandscape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportWeiboImageCmd.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Macros2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextMargin.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Flash.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NotesMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_TableTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Paragraph1.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_3Notes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_1Notes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_WordArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Paragraph1.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Paragraph2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RecentFillColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_1.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_Off.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransOnTime.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CellWidth.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Numbering2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderPlaceHolder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeDiagramNum.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocTranslate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetSlide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPrintHiddenSlide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>cellphoneControl.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransOnClick.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetShape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>cellphoneControl.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChineseTranslation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseIndent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HandoutMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseIndent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToExcel.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintDuplex.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AddSubordinate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioBegin.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitCells.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintCollate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Delete.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChineseTranslation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RewindAudio.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Select.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioCurPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontAlignMenu.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DuplicateSlide.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Numbering.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RewindVideo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoTrim.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BodyContent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPortrait.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewWindow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Security.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitCells.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCells.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideSorter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideVideo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MediaVol.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Backdrop.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Sound.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LoopVideo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ArrangeAll.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PageNumber.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PlayerCapture.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CheckSpelling.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignThaiDistributed.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFill.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ConvertToSmartArtTip.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WppSharePlay.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CreativeCrop.title</source>
        <translation></translation>
    </message>
    <message>
        <source>importtemplates.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InteractiveChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CellHeight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillAndOutLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MediaVol.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderFooter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioFadeIn.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GridGuides.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Find.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFontColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HeaderFooter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Lighting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevFrameSlides.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Ai Matting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PreserveMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CellHeight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ScreenGrabOcr.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomAnimation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Gallery.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportToVideo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBox.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SkipSlide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DrawingToolsDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LoopVideo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Paste.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteNotes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Lighting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LoopAudio.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioPause.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRowsAbove.content</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Macros2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ActionSetting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomFit.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ZoomCombo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_3Notes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToText.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShowSetManualOrAuto.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Markup.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransDuration.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_1Notes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintingOrder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowHideMark.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlidePreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>modelessay.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertColumnsLeft.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignTop.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeTextDir.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertOnlinePicture.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentFix.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_On.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_DrawingTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>onlineMedia.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomAnimation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ConvertToSmartArtTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataPlaceHolder.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OrgChartLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SplitMerge.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertObject.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettingsList_EquationTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignBottom.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Group.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideLayouts.content</source>
        <translation></translation>
    </message>
    <message>
        <source>UsePresenterView.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableSmartStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShowFromCurrent.content</source>
        <translation></translation>
    </message>
    <message>
        <source>OnlineCooperation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertObject.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BordersFill.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertWordArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddAssistant.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HomeDetailedSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PreserveMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RB_Clipboard.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Translate Image.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CreativeCrop.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransOnTime.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Superscript2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeFillAndOutLine.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Bullets2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>StopAutoVersion.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertWordArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioFadeOut.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AddCoworker.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertGeogebra.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RecentFillColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>OrgChartLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FitTextTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>L2RTextDirection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RecentFillColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextBox2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HomeDetailedSettings.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertOnlinePicture.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintCopies.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DistColumnSevenly.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PreviewPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MergeCells.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SetBackground.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShowFromCurrent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Direction.title</source>
        <translation></translation>
    </message>
    <message>
        <source>presentationTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRowsBelow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Backdrop.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewSlide2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevNextPage.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Superscript.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioCurPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AnimationSchemes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RewindAudio.content</source>
        <translation></translation>
    </message>
    <message>
        <source>R2LTextDirection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LockAspectRatio.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableSmartStyle.content</source>
        <translation></translation>
    </message>
    <message>
        <source>3DPresentation.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TaskPane.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CellWidth.title</source>
        <translation></translation>
    </message>
    <message>
        <source>MasterLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingView.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewWindow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideMasterClose.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NotesPageView.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextMargin.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AddAssistant.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_WPP_TextTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ThemeColors.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideDesign.title</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseFontSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseFontSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Thesaurus.title</source>
        <translation></translation>
    </message>
    <message>
        <source>LineBreak.title</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseSpace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseSpace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InvolvedTemplate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InvolvedTemplate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicLine.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Section.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_DrawingTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RenameMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PlayerCapture.title</source>
        <translation></translation>
    </message>
    <message>
        <source>presentationTool.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ActionSetting.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransition.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Flash.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_WPP_TextTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DataPlaceHolder.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoPause.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevPortrait.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PictureToText.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RunMacro.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintCollate.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FullScreenPlay.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertDateTime.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CustomShows.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_Home.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ObjectSelect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Bullets.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Gallery.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Justify.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RB_Font.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RehearseAllSlides.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SpeakerNotes.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ObjectSelect.title</source>
        <translation></translation>
    </message>
    <message>
        <source>CompressPictures.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertMedia.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteMember.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertMedia.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Ai Matting.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Numbering.title</source>
        <translation></translation>
    </message>
    <message>
        <source>StopAutoVersion.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ColorScheme.content</source>
        <translation></translation>
    </message>
    <message>
        <source>wpp2doc.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioAcrossPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewTitleMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Media.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationEditor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Normal.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransApplyToAll.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoPause.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFontColor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>wpp2doc.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TraditionalChinese.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseIndent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettingsList_EquationTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideNumber.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpsAssistMagic.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioPause.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertEduTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>statusbarFontMissing.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlidePreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeEffects.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertOrgChart.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewSlide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Hyperlink.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterName.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AnimationPainter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Distributed.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowButton.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Bullets2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableEraser.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>statusbarFontMissing.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShowSetManualOrAuto.content</source>
        <translation></translation>
    </message>
    <message>
        <source>HideAudio.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetSlide.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideLayout.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewSlideMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NotesPageView.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BackgroundMusic.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevClose.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HideVideo.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_Slides2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideLibrary.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewSlide2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableFontEffects.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SimplifiedChinese.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DynamicShape.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NoteViewVisible.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideLayout.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertOrgChart.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NotesMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RehearseAllSlides.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PreComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>NewComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ExportWeiboImageCmd.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeDiagramStyle.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SmartChoice.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NextComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Superscript2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertSmartArt.content</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoBegin.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowHideGrid.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DistRowSevenly.content</source>
        <translation></translation>
    </message>
    <message>
        <source>EditComment.title</source>
        <translation></translation>
    </message>
    <message>
        <source>BodyContent.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransSound.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextDirection.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SpeakerNotes.title</source>
        <translation></translation>
    </message>
    <message>
        <source>3DPresentation.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevLandscape.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Numbering2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Bullets.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertGeogebra.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SetUpShow.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintPreview.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideShowFromCurrent2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Rehearse.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ThemeColors.title</source>
        <translation></translation>
    </message>
    <message>
        <source>H5LinkManager.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FullScreenPlay.title</source>
        <translation></translation>
    </message>
    <message>
        <source>onlineMedia.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WpPrintWhat_9.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertClipArt.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SelectAll.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WpsAssistOnlineTemplate.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DevelopmentTools.title</source>
        <translation></translation>
    </message>
    <message>
        <source>DecreaseFontSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FontColor2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignThaiDistributed.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoPlay.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignRight.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableOnekeyBeautify.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignCenter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ReadingView.content</source>
        <translation></translation>
    </message>
    <message>
        <source>WorkSpace_Backup.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseFontSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SaveBackgroundPicture.content</source>
        <translation></translation>
    </message>
    <message>
        <source>RunMacro.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RewindVideo.content</source>
        <translation></translation>
    </message>
    <message>
        <source>CompressPictures.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioPlay.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AlignBottom.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintCopies.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Underline.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Find.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransOnClick.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioTrim.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GridGuides.title</source>
        <translation></translation>
    </message>
    <message>
        <source>VideoTrim.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideImage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>RenameMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PrinterName.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableEraser.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertColumnsLeft.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToWord.content</source>
        <translation></translation>
    </message>
    <message>
        <source>LineSpacing.content</source>
        <translation></translation>
    </message>
    <message>
        <source>GraphicFill2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DeleteMaster.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DistColumnSevenly.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideTransSound.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToWord.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WppSharePlay2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PageNumber.title</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatAlignCenter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TableOnekeyBeautify.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShowHideMark.content</source>
        <translation></translation>
    </message>
    <message>
        <source>PreComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideMaster.title</source>
        <translation></translation>
    </message>
    <message>
        <source>H5LinkManager.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewComment.content</source>
        <translation></translation>
    </message>
    <message>
        <source>MorePrintSettings.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ShapeLine2.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DetailedSettings_TableTool.content</source>
        <translation></translation>
    </message>
    <message>
        <source>FormatPainter.content</source>
        <translation></translation>
    </message>
    <message>
        <source>DocumentFix.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideNumber.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrintDirect.content</source>
        <translation></translation>
    </message>
    <message>
        <source>ShadowButton.title</source>
        <translation></translation>
    </message>
    <message>
        <source>EquationEditor.title</source>
        <translation></translation>
    </message>
    <message>
        <source>TextSpeech2.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertColumnsRight.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SetBackground.title</source>
        <translation></translation>
    </message>
    <message>
        <source>Replace.content</source>
        <translation></translation>
    </message>
    <message>
        <source>SlideSorter.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertTable.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PaperSize.content</source>
        <translation></translation>
    </message>
    <message>
        <source>NewDash.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ResetSize.title</source>
        <translation></translation>
    </message>
    <message>
        <source>sp_Macros.content</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertEduTools.content</source>
        <translation></translation>
    </message>
    <message>
        <source>AudioFadeOut.title</source>
        <translation></translation>
    </message>
    <message>
        <source>ChangeTextDir.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TextFontColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>IncreaseSpace.title</source>
        <translation></translation>
    </message>
    <message>
        <source>WebPreview.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PrevNextPage.title</source>
        <translation></translation>
    </message>
    <message>
        <source>PDFToPPT.title</source>
        <translation></translation>
    </message>
    <message>
        <source>SendFileTip.title</source>
        <translation></translation>
    </message>
    <message>
        <source>AutoSaveFile_Off.content</source>
        <translation></translation>
    </message>
    <message>
        <source>Distributed.title</source>
        <translation></translation>
    </message>
    <message>
        <source>InsertRowsBelow.title</source>
        <translation></translation>
    </message>
    <message>
        <source>HighlightColor.content</source>
        <translation></translation>
    </message>
    <message>
        <source>TableFontEffects.content</source>
        <translation></translation>
    </message>
</context>
</TS>
